# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12afSAkWAx8p93CGBIrUtLk0QGqwJI8qd
"""





def start(digits): #this fumction will create random numbers
  result_number=random.randint(10**(digits-1),10**(digits)-1)
  #print(result_number)
  result_number=repetitive_digits(digits,result_number)# repetative number checker
  
  #print(result_number)
  return result_number
  

def repetitive_digits(digits,result_number):#function will check wheather the generated number is repetative or not 
  result_number1=result_number
  list1 = [0,0,0,0,0,0,0,0,0,0] #empty list
 
  res=0
  for i in range(digits): #check every single digit
    n = result_number1 % 10
    list1[n] += 1
   
    result_number1 = result_number1 // 10
  #print(list1)
  for i in range(len(list1)): 
   if list1[i]>1:
      res+=1
      #print('number of Repetitve Digits')
    
  if res > 0:
     
      result_number=start(digits)#fumction call
    
      return result_number
  else:
      print('No Repetitive Digits found in the result number!')
      return result_number
def give_up(result_number): #fuction to end the game
  give=input('do you want to end the game: ')
  if give=='yes':
    print('answer is ', result_number)
  else:
    pass


import random 
digits=int(input('Enter how many digits you want '))
guess_number = 0 #initialise guess_number
guess_number_count = 0
result_number= start(digits)#function call
guess_count=int(input('Enter the maximum number of guesses allowed : ')) #take input fron user that macimun no of gusses

list1 = [0,0,0,0,0,0,0,0,0,0]





while 1<guess_count:
  guess_number=int(input('enter the guess number: '))
  #print(guess_number)
  list2=[0]*digits
  list3=[0]*digits
  n1=result_number
  n2=guess_number
  fermi=0
  pico=0
  bagel=0

  c1=[]
  c2=[]
  
  for i in range(digits): #to make every digit seperate 
    result=n1%10
    guess=n2%10
    n1=n1//10
    n2=n2//10
    c1.append(result) #append every digit in empty list
    c2.append(guess)
  

  for i in c1:
    if i not in c2:
      bagel+=1

  if bagel<digits:
    for i in range(digits):
      for j in range(digits):
        if c1[i]==c2[i] and i==j:
          fermi+=1
        elif c1[i] == c2[j] and i!=j:
          pico+=1
    
    if fermi==digits:
      
      print('Guess Number:', guess_number ,'\t Result:',' Fermi'*fermi)
      print('you win!!!') #if no of fermi are equal to no of digit then game will finish and it shows you win !!!!
      break
    else:
      print('Guess Number:',guess_number,'\t Result:',' Fermi'*fermi,'Pico '*pico)
  if bagel==digits:
       print('Guess Number:', guess_number, '\t Result:',' Bagel') #if the enter number is not equal to random number then it will shoe begal
       
  give_up(result_number)



