# -*- coding: utf-8 -*-
"""Project2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rNNb6qq75gpUQsygDIC8_Ggaq30fJXG0
"""

import random
def start(end):#to start the game (random number will generate)
  z=input('do u want 0 in that digit :')
  
  l=[]
  if z=='Yes':
    while len(l)!=end: 
      r1=random.randint(0,9)
      if r1 not in l:
        l.append(r1)
    #print(l)
    
  elif z=='No':
    while len(l)!=end: 
      r1=random.randint(1,9)
      if r1 not in l:
        l.append(r1)
    #print(l)
    
  return l
def giveup(): #for giveup or end the game
  give=input('do u want to give up:')
  if give=='y':
    print('the answer is' +'/n',r2)
  

digit=int(input('how many digits you want: '))
guess=int(input('how many chances would u like to guess: '))
guess_number=start(digit)
# guess_number=list(guess_number)

output=[]
final=['Fermi']*digit

while 1<guess:
  no=input('enter number: ')
  if len(set(no))==digit:

    no=list(no)

    if len(no)!=digit:
      print('enter'+ str(x)+ 'numbers only ')
      guess-=1
      continue
    else:
      for i in range(len(guess_number)):
        if int(no[i])==guess_number[i]:
          
          output.append('Fermi')
          if output==final:
            break
        elif int(no[i]) in guess_number:
          output.append('Pico')

      if len(output)==0:
        print('Bagels')
      random.shuffle(output)
      #print(output)
      if output==final:
        print('win')
        break
      output.clear()
      
      guess-=1
    
  else:
    print('duplicate no')
    continue

